const React = require("react-native");
 
const { StyleSheet } = React;
 
const TripListStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E5FFF1',
  },
  headerView: {
    width: '100%',
    padding: 5,
    flexDirection: 'row',
    backgroundColor: '#1F487C',
  },
  Headbackground: {
    flexDirection: 'row',
    minHeight: 30,
    width: '100%',
    resizeMode: 'center',
  },
  welcomeText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
  },
  slide: {
    height: 100,
    flex: 1,
    marginHorizontal: 5,
    marginTop: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'lightgray',
    borderRadius: 10,
  },
  rowContainer: {
    flex: 1,
    flexDirection: 'column',
    marginLeft: 5,
    marginRight: 15,
    marginTop: 8,
    marginBottom: 18,
  },
  title: {
    fontSize: 16,
    color: '#000',
  },
  container_text: {
    flex: 1,
    flexDirection: 'column',
    marginLeft: 12,
    justifyContent: 'center',
  },
  description: {
    fontSize: 11,
    fontStyle: 'italic',
  },
  photo: {
    height: 50,
    width: 50,
  },
  image: {
    width: '100%',
    resizeMode: 'cover',
    borderRadius: 10,
    flex: 1,
  },
  trackingView: {
 
    height: 24,
    marginHorizontal: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  wrapper1: {
    position: 'relative',
    flex: 1, // adjust as needed
    height: 65, // adjust as needed
    marginHorizontal: 2,
 
  },
  busPlatformBg: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: '100%',
    height: '100%',
  },
 
  icon: {
    position: 'absolute',
    left: 10,
    top: '54%',
    transform: [{ translateY: -12.5 }],
    width: '50%', // adjust as needed
    height: '50%', // adjust as needed
  }, busListContainer: {
    position: 'relative',
    width: '81%',
    height: 30,
    top: 16,
    left: 26,
  },
  rsText: {
    position: 'absolute',
    top: 4,
    right: 10,
    width: '100%',
    textAlign: 'right',
    color: '#FFFFFF',
    fontFamily: 'Inter',
    fontWeight: '600',
    fontSize: 11,
  },
  list: {
    justifyContent: 'center',
    padding: 5,
  },
  filterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 70,
    height: 30,
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: '#1F487C',
    borderRadius: 5,
    marginRight: 5,
  },
 
  filterTitle: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Inter',
    marginRight: 5,
    textAlign: 'center',
    lineHeight: 14,
  },
  filteAarrowIcon: {
    width: 12,
    height: 6,
  },
  separator: {
    marginVertical: 7,
    borderBottomColor: '#1F487C',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  topBgImage: {
    width: '100%',
    height: 40,
    flexDirection: 'row',
    paddingHorizontal: 5,
    overflow: 'hidden',
    position: 'relative',
    bottom: 5,
  }, topSubView: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0)',
  },
  leftPlaceView: {
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    backgroundColor: 'rgba(0,0,0,0)',
  },
  leftPlaceSubView: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 3,
  },
  fromPlaceTxt: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'right',
    color: 'white',
  },
  fromDateTxt: {
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'white',
  },
  dropPlaceView: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropPlaceTxt: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'left',
    color: 'white',
  },
  buseCountView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    top: 2,
  },
  buseCountTxt: {
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'white',
  },
  busOperatorView: {
    flexDirection: 'row',
    width: '65%',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  operatorNameView: {
    width: '100%',
    height: 34,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomRightRadius: 10,
    borderTopLeftRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
  }, operatorNameTxt: {
    fontSize: 10,
    fontFamily: 'Inter',
    fontWeight: '500',
    textAlign: 'left',
    lineHeight: 12,
    color: 'white',
  }, operatorBrandTxt: {
    fontSize: 15,
    textAlign: 'left',
    fontWeight: '600',
    fontFamily: 'Inter',
    lineHeight: 18,
    color: 'white',
  }, topShareView: {
    backgroundColor: '#FF0000',
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 0,
    borderRightWidth: 15,
    borderBottomWidth: 15,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
  },
  topshareLuxuryView: {
    backgroundColor: '#FF0000',
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 0,
    borderRightWidth: 17,
    borderBottomWidth: 17,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
  },
  compareView: {
    justifyContent: 'center',
    top: 15,
    height: 30,
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  compareGradientView: {
    width: '100%',
    height: 30,
    alignItems: 'center',
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
    justifyContent: 'center',
  },
  comparePriceBtn: {
    flex: 1,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tripRowContainer: {
    flex: 1,
    flexDirection: 'column',
    borderRadius: 20,
    top: 15,
    borderWidth: 1,
    borderColor: 'rgba(31, 72, 124, 0.5)',
    backgroundColor: '#FFF',
    elevation: 2,
    // shadowColor: 'gray',
    // shadowOpacity: 0.8,
    // shadowRadius: 2,
    // shadowOffset: {
    //   height: 1,
    //   width: 0,
    // },
  },
  tripBusTypeTxt: {
    fontSize: 10,
    padding: 5,
    lineHeight: 12,
    fontFamily: 'Inter',
    fontWeight: '400',
    textAlign: 'center',
    color: '#1F487C',
  },
  tripPickDateView: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    height: 40,
    marginTop: 10,
  },
  tripDateTxt: { fontSize: 12, lineHeight: 15, fontFamily: 'Inter', fontWeight: '400', color: '#1F487C', textAlign: 'left' },
  LuxtripDateTxt: { fontSize: 12, lineHeight: 15, fontFamily: 'Inter', fontWeight: '400', color: '#393939', textAlign: 'left' },
  tripStartTimeTxt: {
    fontSize: 14,
    lineHeight: 19, fontFamily: 'Inter', fontWeight: '700', color: '#1F487C', textAlign: 'left'
  },
  LuxtripStartTimeTxt: {
    fontSize: 14,
    lineHeight: 19, fontFamily: 'Inter', fontWeight: '700', color: '#393939', textAlign: 'left'
 
  },
  tripDropView: {
    flex: 1,
    paddingHorizontal: 5,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 1,
  },
  tripDurationTimeTxt: {
    position: 'absolute',
    top: 10,
    left: 5,
    width: '100%',
    textAlign: 'center',
    color: '#FFFFFF',
    fontFamily: 'Inter',
    fontWeight: '600',
    lineHeight: 12,
 
    fontSize: 10,
  },
  tripDropDateView: {
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 3,
    alignItems: 'center',
  },
  tripDropDateTxt: {
    fontSize: 14, lineHeight: 19, fontFamily: 'Inter', fontWeight: '700', color: '#1F487C', textAlign: 'right'
  },
  LuxtripDropDateTxt: {
    fontSize: 14, lineHeight: 19, fontFamily: 'Inter', fontWeight: '700', color: '#393939', textAlign: 'right'
  },
  tripViewDivide: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  tripRightView: {
    flexDirection: 'row',
    borderColor: '#2CA103',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 25,
    borderRadius: 5,
  },
  tripStarView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#2CA103',
  },
  ratingTxt: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '400',
    color: '#FFFFFF',
    fontFamily: 'Inter',
  },
  userView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    overflow: 'hidden'
  },
  userLikeCount: {
    fontSize: 11,
    color: '#2CA103',
    lineHeight: 13,
    fontWeight: '400',
    textAlign: 'left',
    fontFamily: 'Inter',
  },
  seatRemainView: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 193, 193, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    height: 25,
    borderRadius: 12,
  },
  seatCountTxt: {
    fontSize: 11,
    textAlign: 'justify',
    color: '#C62B2B',
    fontWeight: '600',
    fontFamily: 'Inter',
    lineHeight: 14,
  },
  a_seats: {
    fontSize: 12,
    textAlign: 'center',
    color: '#C62B2B',
    fontWeight: '600',
    fontFamily: 'Inter',
    lineHeight: 14,
  },
 
  windowSeatTxt: {
    fontSize: 13,
    color: '#1F487C',
    fontWeight: '500',
    textAlign: 'center',
    lineHeight: 16,
    fontFamily: 'Inter',
  },
  tripViewMoreTxt: {
    fontSize: 12.07,
    color: '#1F487C',
    fontFamily: 'Inter',
    fontWeight: '400',
    lineHeight: 15,
  },
  viewMoreDivide: {
    borderStyle: 'solid',
    margin: 4,
    borderWidth: 0.5,
    borderRadius: 1,
    borderColor: '#1F487C',
    height: '80%',
    width: 1,
  },
  liveTrackingTxt: {
    fontSize: 12.07,
    color: '#1F487C',
    paddingHorizontal: 3,
    fontFamily: 'Inter',
    fontWeight: '400',
    lineHeight: 15,
  },
  LowPriceRightShape: {
    position: 'absolute',
    right: -9,
    top: 44,
    bottom: 3,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderRightWidth: 9,
    borderTopWidth: 10,
    borderRightColor: "transparent",
    borderTopColor: '#1F487C'
  },
  lowPriceImageView: {
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    height: 66,
    width: 66,
    borderRadius: 100,
    position: 'absolute',
    left: 0,
    top: -8,
    paddingLeft: 5,
  },
  tripPriceTxt: {
    marginRight: 20,
    fontSize: 20,
    lineHeight: 24,
    fontFamily: 'Inter',
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '600',
 
  },
  tripBusName: {
    marginLeft: 15,
    fontSize: 14,
    color: '#FFFFFF',
    textAlign: 'left',
    fontWeight: '700',
    lineHeight: 19,
  },
  tripBusnameView: {
    backgroundColor: '#1F487C',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 34,
    width: '100%',
    borderTopRightRadius: 10,
    position: 'relative',
    left: 15,
    flexDirection: 'row',
    marginTop: 10,
  },
 SkeletonView: {
  height: 170,
  borderRadius:10,
  marginHorizontal:5,
  marginVertical:5,
  paddingHorizontal:10,
  paddingVertical:5,
  backgroundColor:"white",
  borderWidth: 1, // Border thickness
  borderColor: "#1F487C", // Border color
  borderStyle: "solid", // (Optional) Default is solid
}
});
 
 
export default TripListStyle;